### ISSUE TITLE
Cant run the setup

### ISSUE THREAD

**Issue by KingAlawaka** [nipy/nireg#6]
This is the error message im getting. Thank you
> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/king/opencv_codes/nireg/nireg/__init__.py", line 4, in <module>
    from .resample import resample
  File "/home/king/opencv_codes/nireg/nireg/resample.py", line 11, in <module>
    from ._register import (_cspline_transform,
ImportError: No module named 'nireg._register'

>

**Comment by sohrabtowfighi** [comment]
The following worked perfectly for me
pip install git+https://github.com/nipy/nireg.git
